### ISSUE TITLE
Tela de relatório não detalha a média por campanha

### ISSUE THREAD

**Issue by frchico** [CBSIIFSLagarto/VotoIFS#40]
O relatório (ver #6) não está apresentando a média de votos por campanha. 

Interessante mostrar assim:

Campanha | De | Até | Média
-------------|:-:|:-:|:---------:
Teste 1 |11/11/2019| 21/11/2019| 5.0
Teste 2 |12/11/2019| 22/11/2019| 4.0
Teste 3 |13/11/2019| 23/11/2019| 2.0

**Comment by willfarias141** [comment]
O relatório apresenta sim a média de votos por campanha.

**Comment by willfarias141** [comment]
A diferença é que na tabela que fizemos contém, logo abaixo da campanha, a listagem de votos recebidos. Vou retirar a listagem dos votos e a tabela atenderá ao solicitado nessa tarefa.
